alertmanager:
  enabled: false
kubeStateMetrics:
  enabled: false
nodeExporter:
  enabled: false
pushgateway:
  enabled: false
server:
  persistentVolume:
    enabled: false
  global:
    scrape_interval: 10s
    scrape_timeout: 10s
