concourse:
    web:
        externalUrl: http://concourse.mydomain.com
        bindPort: 80
        localAuth:
            enabled: true
        auth:
            mainTeam:
                config: |
                  roles:
                  - name: owner
                    local:
                      users: ["admin"]
                localUser: "admin"

                # Uncomment if you want to enable GitHub authentication with your organization.
                #github:
                #    org: mygithuborg
            github:
                # Set to true to enable GitHub integration.
                # You will need to set values for GitHub properties.
                # You may want to disable local authentication in this case.
                enabled: false
        kubernetes:
            enabled: true
web:
    service:
        type: LoadBalancer
secrets:
    githubClientId: clientIdInGitHubSettings
    githubClientSecret: clientSecretInGitHubSettings
    localUsers: "admin:changeme"
